version: "3.8"
services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    command: ["uvicorn", "app.main:app", "--reload",  "--host", "0.0.0.0", "--port", "8000"]
    restart: always
    working_dir: /backend
    ports:
      - 8000:8000
    volumes:
      - ./backend/app:/backend/app
      - ./backend/tests:/backend/tests

