version: "3.8"
services:

  db:
    image: postgres
    container_name: pgdb
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ./backend/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 80s
    volumes:
      - clisto-pgdb-data:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    env_file:
      - ./backend/.env
    volumes:
      - clisto-pgadmin-data:/var/lib/pgadmin
    depends_on:
      db:
        condition: service_healthy

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    command: ["uvicorn", "app.main:app", "--reload",  "--host", "0.0.0.0", "--port", "8000"]
    restart: always
    working_dir: /backend
    ports:
      - 8000:8000
    volumes:
      - ./backend/app:/backend/app
      - ./backend/tests:/backend/tests
      - ./backend/migrations:/backend/migrations
    links:
      - db
    depends_on:
      db:
        condition: service_healthy

volumes:
  clisto-pgadmin-data:
  clisto-pgdb-data:
