"""empty message

Revision ID: 3903810effc5
Revises: 9408aa945990
Create Date: 2023-10-12 20:19:27.293196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3903810effc5'
down_revision: Union[str, None] = '9408aa945990'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maintenance_services', sa.Column('description', sa.String(), nullable=True))
    op.add_column('maintenance_services', sa.Column('video_url', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('maintenance_services', 'video_url')
    op.drop_column('maintenance_services', 'description')
    # ### end Alembic commands ###
